---
- name: don't install ruby docs
  lineinfile:
    dest:   /usr/local/etc/gemrc
    create: true
    regexp: "^gem: --no-document"
    line:    "gem: --no-document"

- name: install ruby from source
  include: install-from-source.yml
  when: ruby_from_source

- name: install ruby - RedHat
  yum: name={{ item }} state=present
  with_items:
    - ruby
    - rubygems
  when: ansible_os_family == 'RedHat' and not ruby_from_source

- name: install ruby - Debian
  apt: name={{ item }} state=present
  with_items:
    - ruby
  when: ansible_os_family == 'Debian' and not ruby_from_source

- name: put rubygems on path
  template:
    src: "rubygems.sh.j2"
    dest: "/etc/profile.d/rubygems.sh"
  become: true

- name: update rubygems
  shell: "gem update --system"
  register: result
  changed_when: "'Latest version currently installed' not in result.stdout"

- name: Install Bundler.
  gem:
    name: bundler
    state: present
    user_install: no
