---
- name: install ruby - RedHat
  yum: name={{ item }} state=present
  with_items:
    - ruby
    # - ruby-devel
  when: ansible_os_family == 'RedHat'

- name: install ruby - Debian
  apt: name={{ item }} state=present
  with_items:
    - ruby
    # - ruby-devel
  when: ansible_os_family == 'Debian'

- name: set GEM_HOME & GEM_PATH for all users and put the gem executable directory in everyone's PATH
  template:
    src: "templates/ruby.sh.j2"
    dest: "/etc/profile.d/ruby.sh"

- name: update rubygems
  shell: "gem update --system"
  register: result
  changed_when: "'Latest version currently installed' not in result.stdout"

- name: Install Bundler.
  gem:
    name: bundler
    state: present
    user_install: no
